language: node_js
cache:
  directories:
  - node_modules
node_js:
- node
before_install:
- '[[ $(node -v) =~ ^v9.*$ ]] || npm install -g npm@latest'
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: ErCSthIHnLcrUeneL9Ewx/IgM0aiOm5rtfbHCMtwbM0cfxTmloJXnC8loftoceCAK8rjDPNSUY21+cyOMjLELT5/sh9PTtdBwwzwiovfu+4/4NWQcw8e4ZUrDU6JRT77H7n6++WlIOn6t153vFhSga5R/PVvaLVktHFbL4mFuNCBw7TiKRqSl0xkqO4QKTGkuq1i4EXeIEdsEuuwUtmPZzcgB4CWRa4NZJyaAfhn07V9Hy8hozhVLYsGjj+pAbafN30Xd5klZXKUmg27l8Eol9ZUdnxjBIci6RLuLg/wFFJGcu2SS5WgKpwAL4vZPvjj5wpHZmBuVuDGm2mO1GpdZsJRA1kx13h8sAe8Ld5JVSE3DrKm4DJ8FKvb3P6JGXJ6u6TYW9JEDPHHv5a8zWp+vXmnKCXCB7F+btc6O462dACRDmtOvt2nQdlEL72r6ZwUaCd48NfzwirrAuciNw058YU5mVsjr8IQ2594+axpn5m4b+5ACPfVppzUl+MIt4WHGgOKTblNw6pAfEOq2NzSmtH2ywmFZEhzLiYSphuTH3n0FdyoEi3ztB+nLwLWcztk0z8Tx2Rj1lTx/Um+Cxg4Ge7pL9T/MA9Yp9YycKkSyXSbg921CGIj4R3kgEwNgWzL2vftDS+pl6wSJFYag+YAw5BMU8RbCm9yfd3W5fFCNzA=
